### ISSUE TITLE
Globally unique person identifier

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-types-contact#3]
Polish client developers reported that it would be useful for them if servers would include a person identifier, preferably globally unique one.

The only method of achieving this seems to build on [National identification numbers](https://en.wikipedia.org/wiki/National_identification_number). This is private data, so it's not 100% clear if all countries would supply it. However, as far as I know, most partners store this information, and might provide it.

It's worth noting, that a single person might have multiple national identifiers. There are many reasons for that, e.g.

* Citizenship can be changed, a person might be identified by both national numbers in this case (the new one and the old one).
* [Dual citizenship](https://en.wikipedia.org/wiki/Multiple_citizenship).
* In some countries national identification numbers are mutable (not truly unique).
* I'm not sure, but after studying wikipedia page, I suspect that in some countries it's not certain which of the various identification numbers is the "primary one". So, developers in those countries might want to provide more than one. (However, we should recommend that servers provide a single, unique one.) Despite this, I suspect it's safe to assume that we don't need any additional "subtype" - that is, for each country, if an identifier of a person is given, developers will be able to uniquely identify this person without knowing with type of the identifier it is.

I propose the following format:

```
ZA-8001015009087
PL-83120453012
NO-04128353012
```

So, it's a ISO 3166-1 alpha-2 code, followed by a dash, and then the national ID number.

**Comment by wrygiel** [comment]
@erasmus-without-paper/all-members

**Comment by wrygiel** [comment]
No comments here, so I will assume that it's okay to introduce this as described above.

**Comment by wrygiel** [comment]
@erasmus-without-paper/all-members, please review:

https://github.com/erasmus-without-paper/ewp-specs-types-person-id/tree/v0.1.1

If it's okay with all of you, we will include optional "UPIDs" in all places where persons are referenced.

**Comment by wrygiel** [comment]
I guess that this idea hasn't gained enough traction. Should we drop this repository from the Developers page?

**Comment by janinamincer-daszkiewicz** [comment]
No. This is important, we may come back to this idea some time in the future.
