### ISSUE TITLE
Role vs contact-name

### ISSUE THREAD

**Issue by lennertVanSever** [erasmus-without-paper/ewp-specs-types-contact#5]
<img width="522" alt="screen shot 2018-04-06 at 18 12 06" src="https://user-images.githubusercontent.com/23064517/38431905-11be9038-39c6-11e8-9bc4-b59c293b359c.png">

In this screenshot from the [EWP data model](https://github.com/erasmus-without-paper/ewp-wp3-data-model) you can see that the a **Role** is specified as a primary key. Above the table you can see that a role can be: 
- Admission 
- Housing
- Course Cat 
- Visas
- Insurance 
- IRO
- ... (other not specified values)

If I understand correctly, the [schema](https://github.com/erasmus-without-paper/ewp-specs-types-contact/blob/stable-v1/schema.xsd) specifies that a role must be defined as a **contact-name** which can occur an unbounded amount of times and it can have any value. Now, this is quite contradicting the data model since it says that it should be a primary key.

In my application, it would be really handy to have predefined roles. For example, a student/institution wants to know the contact details of the admission department. Then I can just search for the role "admission" in the contacts from an institution/organisation unit. But now institutions can define the roles however they want so I can't search for specific predefined one.

**Comment by kamil-olszewski-uw** [comment]
Data type **Contact** in the shcema has no strict role definition. Role may be deduced from elements **contact-name** and **role-description**, but we can't search for specific role.

In some APIs role is determined by the name of element. For example: we have element **signing-contact** in **get** endpoint of **Interinstitutional Agreements API**. Moreover, it is suggested that **Contact** type may be extended by inheriting data type in future major updates.

Optional subelement of type **Contact** with choices limited to set of predefined roles seems useful. If universities would find it helpful, it may be introduced as part of some future update. But there is not certainty that such data is stored in HEIs' databases.

**Comment by georgschermann** [comment]
Currently mapped in MO:

Function of ‘Head of Institution‘ 
Function of ‘Legal Representative‘ 
Function of international coordinator 
ECTS Institutional Coordinator 
Function of institutional coordinator 
Function of ‘Departmental Coordinator (Outgoing)‘ 
Function of ‘Departmental Coordinator (Incoming)‘ 
Function of ‘Teaching Staff‘
Function of ‘Head of department‘ 
Function of the contact person at the partner institution
Function of contact person at the own institution
Function of ‘Tutor‘ 
Function of ‘Mentor‘
Function of ‘Promotor of the vacancy at the home institution‘ 
Function of ‘Visa assistance‘
Function of ‘Insurance assistance‘ 
Function of ‘Housing assistance‘ 
Function ‘Administrator contract (budget)‘ 
Function ‘Own contract (budget)‘
